# Generated by Django 3.2 on 2024-10-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('price',), 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='static/images/'),
        ),
    ]
